// <auto-generated />
using System;
using AluraFlixServer.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AluraFlixServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230308160801_CreateUser")]
    partial class CreateUser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AluraFlixServer.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Color = "#FFFFFF",
                            Title = "LIVRE"
                        });
                });

            modelBuilder.Entity("AluraFlixServer.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("AluraFlixServer.Models.Video", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Videos");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4edc4fc9-8da8-4494-8d96-d283541f73f3"),
                            CategoryId = 1,
                            Description = "O anime mais injustiçado da temporada (na minha humilde opinião haha) voltou! Nier Automata 1.1a ep. 4 comentado em detalhes aqui pra vocês.",
                            Title = "QUE BATALHA EMOCIONANTE!! ELE VOLTOU!",
                            Url = "https://www.youtube.com/watch?v=zZvRCSlkH18"
                        },
                        new
                        {
                            Id = new Guid("a266184a-afbb-4446-a1f5-361785f9af45"),
                            CategoryId = 1,
                            Description = "2V2  @prohooper4533    Nosso SEGUNDO desafio do grupo de racha, as próximas semanas, vou fazer um vídeo explicando o intuito dos novos desafio aqui do canal e do PRO HOOPER, espero que vocês gostem e até o próximo video familina, tmj!",
                            Title = "ARREMESSEI IGUAL O STEPHEN CURRY E ACABEI COM O JOGO!!!",
                            Url = "https://www.youtube.com/watch?v=GIYtwPu5Heo&t=166s"
                        },
                        new
                        {
                            Id = new Guid("6ab33bb2-cbd4-4446-81d4-c3efd739f2e1"),
                            CategoryId = 1,
                            Description = "Depoimento Ange Emanuelle na Alura",
                            Title = "Dev Front-end: a trajetória de uma programadora e Alura Star | Angela Emanuelle",
                            Url = "https://www.youtube.com/watch?v=ODEgEk83PLA"
                        },
                        new
                        {
                            Id = new Guid("c7384eb0-4876-4ec6-84c3-f12b324abaa6"),
                            CategoryId = 1,
                            Description = "Kang VS THANOS, EINERD explicação com Peter JORDAN",
                            Title = "DEFINITIVO! KANG VS THANOS, QUEM É O PIOR E MAIS CRUEL?",
                            Url = "https://www.youtube.com/watch?v=umTFii323Lg"
                        });
                });

            modelBuilder.Entity("AluraFlixServer.Models.Video", b =>
                {
                    b.HasOne("AluraFlixServer.Models.Category", "Category")
                        .WithMany("Videos")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("AluraFlixServer.Models.Category", b =>
                {
                    b.Navigation("Videos");
                });
#pragma warning restore 612, 618
        }
    }
}
